"""changesv3

Revision ID: 956b5ccf1e49
Revises: 03fcf8a3eb34
Create Date: 2025-03-17 18:32:14.302338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '956b5ccf1e49'
down_revision: Union[str, None] = '03fcf8a3eb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='status').create(op.get_bind())
    sa.Enum('DEPOSIT', 'WITHDRAW', 'TRANSFER', name='transactionaction').create(op.get_bind())
    op.add_column('transaction_logs', sa.Column('action', postgresql.ENUM('DEPOSIT', 'WITHDRAW', 'TRANSFER', name='transactionaction', create_type=False), nullable=True))
    op.add_column('transaction_logs', sa.Column('arguments', sa.JSON(), nullable=True))
    op.alter_column('transaction_logs', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='status'),
               existing_nullable=True,
               postgresql_using='status::status')
    op.create_index(op.f('ix_transaction_logs_action'), 'transaction_logs', ['action'], unique=False)
    op.drop_column('transaction_logs', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_logs', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transaction_logs_action'), table_name='transaction_logs')
    op.alter_column('transaction_logs', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('transaction_logs', 'arguments')
    op.drop_column('transaction_logs', 'action')
    sa.Enum('DEPOSIT', 'WITHDRAW', 'TRANSFER', name='transactionaction').drop(op.get_bind())
    sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='status').drop(op.get_bind())
    # ### end Alembic commands ###
