"""changesv3

Revision ID: 0c66f6ab8c43
Revises: 6502d121c208
Create Date: 2025-03-17 18:32:39.898665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c66f6ab8c43'
down_revision: Union[str, None] = '6502d121c208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('instabingo_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instabingo_id'], ['instabingos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_numbers_id'), 'numbers', ['id'], unique=False)
    op.add_column('games', sa.Column('numbers', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('games', sa.Column('event_start', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('event_end', sa.DateTime(), nullable=True))
    op.add_column('instabingos', sa.Column('winnings', sa.JSON(), nullable=True))
    op.drop_column('instabingos', 'prize')
    op.add_column('tickets', sa.Column('instabingo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'instabingos', ['instabingo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'instabingo_id')
    op.add_column('instabingos', sa.Column('prize', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=False))
    op.drop_column('instabingos', 'winnings')
    op.drop_column('games', 'event_end')
    op.drop_column('games', 'event_start')
    op.drop_column('games', 'numbers')
    op.drop_index(op.f('ix_numbers_id'), table_name='numbers')
    op.drop_table('numbers')
    # ### end Alembic commands ###
