"""changesv8

Revision ID: 1dfe0cc6f5ca
Revises: 399c66f86cf8
Create Date: 2025-03-21 08:28:12.888326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dfe0cc6f5ca'
down_revision: Union[str, None] = '399c66f86cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='ticketstatus').create(op.get_bind())
    op.alter_column('games', 'prize',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.add_column('tickets', sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'CANCELLED', name='ticketstatus', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    op.alter_column('games', 'prize',
               existing_type=sa.String(length=256),
               type_=sa.NUMERIC(precision=9, scale=2),
               existing_nullable=True)
    sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='ticketstatus').drop(op.get_bind())
    # ### end Alembic commands ###
