"""read&totp

Revision ID: fc95ac4d9dc4
Revises: d20a701c35ee
Create Date: 2025-04-21 19:00:57.935854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision: str = 'fc95ac4d9dc4'
down_revision: Union[str, None] = 'd20a701c35ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('read', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('totp', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp')
    op.drop_column('notifications', 'read')
    # ### end Alembic commands ###
