"""changesv6

Revision ID: 5e9d4fd94274
Revises: c613eb79c358
Create Date: 2025-02-17 19:44:51.714862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9d4fd94274'
down_revision: Union[str, None] = 'c613eb79c358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('games', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='gamestatus'), nullable=True))
    op.alter_column('jackpot_instances', 'jackpot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('jackpots', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('jackpots', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='gamestatus'), nullable=True))
    op.create_foreign_key(None, 'jackpots', 'currencies', ['currency_id'], ['id'])
    op.add_column('tickets', sa.Column('game_id', sa.Integer(), nullable=True))
    op.drop_constraint('tickets_game_instance_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'games', ['game_id'], ['id'])
    op.drop_column('tickets', 'game_instance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('game_instance_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_game_instance_id_fkey', 'tickets', 'game_instances', ['game_instance_id'], ['id'])
    op.drop_column('tickets', 'game_id')
    op.drop_constraint(None, 'jackpots', type_='foreignkey')
    op.drop_column('jackpots', 'status')
    op.drop_column('jackpots', 'currency_id')
    op.alter_column('jackpot_instances', 'jackpot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('games', 'status')
    op.drop_column('games', 'image')
    # ### end Alembic commands ###
