"""changesv3

Revision ID: 66a04cad0fd1
Revises: aa01083d0cb7
Create Date: 2025-02-07 11:07:26.545826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a04cad0fd1'
down_revision: Union[str, None] = 'aa01083d0cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jackpots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('_type', sa.Enum('GLOBAL', 'LOCAL', name='jackpottype'), nullable=False),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(), nullable=True),
    sa.Column('tzone', sa.Integer(), nullable=True),
    sa.Column('repeat', sa.Boolean(), nullable=True),
    sa.Column('repeat_days', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jackpots_id'), 'jackpots', ['id'], unique=False)
    op.create_table('jackpot_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jackpot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='jackpotstatus'), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jackpot_id'], ['jackpots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jackpot_instances_id'), 'jackpot_instances', ['id'], unique=False)
    op.drop_column('games', 'as_default')
    op.drop_column('games', 'timezone')
    op.add_column('tickets', sa.Column('jackpot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'jackpots', ['jackpot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'jackpot_id')
    op.add_column('games', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('as_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_jackpot_instances_id'), table_name='jackpot_instances')
    op.drop_table('jackpot_instances')
    op.drop_index(op.f('ix_jackpots_id'), table_name='jackpots')
    op.drop_table('jackpots')
    # ### end Alembic commands ###
