"""changesv8

Revision ID: 90fa4e9491e5
Revises: 9bcc1ee8a6c3
Create Date: 2025-02-26 17:37:56.101827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fa4e9491e5'
down_revision: Union[str, None] = '9bcc1ee8a6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_change_history', 'previous_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('kyc', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('document', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'document')
    op.drop_column('users', 'kyc')
    op.alter_column('balance_change_history', 'previous_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
