"""changesv7

Revision ID: 9bcc1ee8a6c3
Revises: 5e9d4fd94274
Create Date: 2025-02-19 16:33:42.110476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcc1ee8a6c3'
down_revision: Union[str, None] = '5e9d4fd94274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE status AS ENUM ('PENDING', 'SUCCESS', 'CANCELED', 'INSUFFICIENT_FUNDS', 'WEB3_ERROR')")
    op.execute("CREATE TYPE gameview AS ENUM ('MONETARY', 'MATERIAL')")
    op.add_column('balance_change_history', sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'CANCELED', 'INSUFFICIENT_FUNDS', 'WEB3_ERROR', name='status'), nullable=True))
    op.add_column('balance_change_history', sa.Column('args', sa.String(), nullable=True))
    op.add_column('games', sa.Column('kind', sa.Enum('MONETARY', 'MATERIAL', name='gameview'), nullable=True))
    op.add_column('games', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('jackpots', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jackpots', 'deleted')
    op.drop_column('games', 'deleted')
    op.drop_column('games', 'kind')
    op.drop_column('balance_change_history', 'args')
    op.drop_column('balance_change_history', 'status')
    op.execute('DROP TYPE status')
    op.execute('DROP TYPE gameview')
    # ### end Alembic commands ###
