"""changesv6

Revision ID: b39860661072
Revises: f4386326a108
Create Date: 2025-03-18 12:00:18.519291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39860661072'
down_revision: Union[str, None] = 'f4386326a108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('referral_links_name_key', 'referral_links', type_='unique')
    op.create_index(op.f('ix_referral_links_link'), 'referral_links', ['link'], unique=False)
    op.drop_column('referral_links', 'placement')
    op.add_column('users', sa.Column('telegram', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'telegram')
    op.add_column('referral_links', sa.Column('placement', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_referral_links_link'), table_name='referral_links')
    op.create_unique_constraint('referral_links_name_key', 'referral_links', ['name'])
    # ### end Alembic commands ###
