"""changesv10

Revision ID: e0c164f82b4c
Revises: 23d00ee3ccf8
Create Date: 2025-03-12 08:51:02.602965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'e0c164f82b4c'
down_revision: Union[str, None] = '23d00ee3ccf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'deleted')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gamestatus',
        new_values=['PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'DELETED'],
        affected_columns=[TableReference(table_schema='public', table_name='game_instances', column_name='status'), TableReference(table_schema='public', table_name='games', column_name='status'), TableReference(table_schema='public', table_name='jackpots', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gamestatus',
        new_values=['PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='game_instances', column_name='status'), TableReference(table_schema='public', table_name='games', column_name='status'), TableReference(table_schema='public', table_name='jackpots', column_name='status')],
        enum_values_to_rename=[],
    )
    op.add_column('games', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
