"""changesv5

Revision ID: f4386326a108
Revises: f8af0e065fab
Create Date: 2025-03-18 07:07:31.760797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4386326a108'
down_revision: Union[str, None] = 'f8af0e065fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_id'), 'kyc', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_id'), table_name='kyc')
    op.drop_table('kyc')
    # ### end Alembic commands ###
