"""last_session

Revision ID: 5a1b80eb4a8d
Revises: dcfca5b9f590
Create Date: 2025-05-08 10:59:47.949691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision: str = '5a1b80eb4a8d'
down_revision: Union[str, None] = 'dcfca5b9f590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_session', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_session')
    # ### end Alembic commands ###
