"""changesv11

Revision ID: 4ca4919e8c4c
Revises: 6704619dc122
Create Date: 2025-03-04 21:13:19.085512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca4919e8c4c'
down_revision: Union[str, None] = '6704619dc122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.drop_column('users', 'firtname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firtname', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
