"""changesv11

Revision ID: 8a588b07669e
Revises: c123ad8aa586
Create Date: 2025-03-26 19:09:42.086162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a588b07669e'
down_revision: Union[str, None] = 'c123ad8aa586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NONE', 'WEEKLY', 'MONTHLY', 'YEARLY', name='repeattype').create(op.get_bind())
    op.add_column('jackpots', sa.Column('repeat_type', postgresql.ENUM('NONE', 'WEEKLY', 'MONTHLY', 'YEARLY', name='repeattype', create_type=False), nullable=True))
    op.drop_column('jackpots', 'repeat_days')
    op.drop_column('jackpots', 'repeat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jackpots', sa.Column('repeat', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('jackpots', sa.Column('repeat_days', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('jackpots', 'repeat_type')
    sa.Enum('NONE', 'WEEKLY', 'MONTHLY', 'YEARLY', name='repeattype').drop(op.get_bind())
    # ### end Alembic commands ###
