"""changesv2

Revision ID: aa01083d0cb7
Revises: b1d136da8ca4
Create Date: 2025-02-06 09:40:49.199812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa01083d0cb7'
down_revision: Union[str, None] = 'b1d136da8ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firtname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firtname')
    # ### end Alembic commands ###
