"""changesv9

Revision ID: d0019f2c5a5c
Revises: 90fa4e9491e5
Create Date: 2025-02-27 13:23:16.784108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0019f2c5a5c'
down_revision: Union[str, None] = '90fa4e9491e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('placement', sa.String(length=256), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_referral_links_id'), 'referral_links', ['id'], unique=False)
    op.add_column('users', sa.Column('referral_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'referral_links', ['referral_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referral_id')
    op.drop_index(op.f('ix_referral_links_id'), table_name='referral_links')
    op.drop_table('referral_links')
    # ### end Alembic commands ###
