"""Initial migration for second_db

Revision ID: 1afc28d28a6a
Revises: 
Create Date: 2025-03-14 14:15:56.291159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1afc28d28a6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LOGIN', 'LOGOUT', 'REGISTER', 'DEPOSIT', 'WITHDRAW', 'TRANSACTION', 'UPDATE', 'ADMIN_LOGIN', 'ADMIN_LOGOUT', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_DELETE', name='action').create(op.get_bind())
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_time', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_request_logs_method'), 'request_logs', ['method'], unique=False)
    op.create_index(op.f('ix_request_logs_url'), 'request_logs', ['url'], unique=False)
    op.create_table('transaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_logs_id'), 'transaction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_status'), 'transaction_logs', ['status'], unique=False)
    op.create_index(op.f('ix_transaction_logs_transaction_id'), 'transaction_logs', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_user_id'), 'transaction_logs', ['user_id'], unique=False)
    op.create_table('user_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', postgresql.ENUM('LOGIN', 'LOGOUT', 'REGISTER', 'DEPOSIT', 'WITHDRAW', 'TRANSACTION', 'UPDATE', 'ADMIN_LOGIN', 'ADMIN_LOGOUT', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_DELETE', name='action', create_type=False), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_action_logs_action'), 'user_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_user_action_logs_id'), 'user_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_action_logs_user_id'), 'user_action_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_action_logs_user_id'), table_name='user_action_logs')
    op.drop_index(op.f('ix_user_action_logs_id'), table_name='user_action_logs')
    op.drop_index(op.f('ix_user_action_logs_action'), table_name='user_action_logs')
    op.drop_table('user_action_logs')
    op.drop_index(op.f('ix_transaction_logs_user_id'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_transaction_id'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_status'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    op.drop_index(op.f('ix_request_logs_url'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_method'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.drop_table('request_logs')
    sa.Enum('LOGIN', 'LOGOUT', 'REGISTER', 'DEPOSIT', 'WITHDRAW', 'TRANSACTION', 'UPDATE', 'ADMIN_LOGIN', 'ADMIN_LOGOUT', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_DELETE', name='action').drop(op.get_bind())
    # ### end Alembic commands ###
