"""block

Revision ID: cda6ab01730e
Revises: bf55d8fb5993
Create Date: 2025-05-28 16:55:39.530995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'cda6ab01730e'
down_revision: Union[str, None] = 'bf55d8fb5993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['LOGIN', 'LOGOUT', 'REGISTER', 'DEPOSIT', 'WITHDRAW', 'TRANSACTION', 'UPDATE', 'OTHER', 'ADMIN_LOGIN', 'ADMIN_LOGOUT', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_DELETE', 'OP_BLOCK', 'BLOCK'],
        affected_columns=[TableReference(table_schema='public', table_name='user_action_logs', column_name='action')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['LOGIN', 'LOGOUT', 'REGISTER', 'DEPOSIT', 'WITHDRAW', 'TRANSACTION', 'UPDATE', 'OTHER', 'ADMIN_LOGIN', 'ADMIN_LOGOUT', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_DELETE'],
        affected_columns=[TableReference(table_schema='public', table_name='user_action_logs', column_name='action')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
