"""changesv5

Revision ID: a8012d142ecf
Revises: 0e1cdd40eade
Create Date: 2025-05-11 11:23:34.013447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8012d142ecf'
down_revision: Union[str, None] = '0e1cdd40eade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hidden_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', postgresql.ENUM('TOTAL_SOLD_TICKETS', 'ARPU', 'ARPPU', 'LTV', 'GGR', 'FTD', 'CPA', 'DAU', 'AVG_SESSION_TIME', name='metrictype', create_type=False), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hidden_metrics_id'), 'hidden_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_hidden_metrics_metric_name'), 'hidden_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_hidden_metrics_user_id'), 'hidden_metrics', ['user_id'], unique=False)
    op.add_column('metrics', sa.Column('country', sa.String(length=32), nullable=True))
    op.drop_index('ix_metrics_name', table_name='metrics')
    op.create_index(op.f('ix_metrics_country'), 'metrics', ['country'], unique=False)
    op.add_column('user_action_logs', sa.Column('country', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_action_logs_country'), 'user_action_logs', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_action_logs_country'), table_name='user_action_logs')
    op.drop_column('user_action_logs', 'country')
    op.drop_index(op.f('ix_metrics_country'), table_name='metrics')
    op.create_index('ix_metrics_name', 'metrics', ['name'], unique=False)
    op.drop_column('metrics', 'country')
    op.drop_index(op.f('ix_hidden_metrics_user_id'), table_name='hidden_metrics')
    op.drop_index(op.f('ix_hidden_metrics_metric_name'), table_name='hidden_metrics')
    op.drop_index(op.f('ix_hidden_metrics_id'), table_name='hidden_metrics')
    op.drop_table('hidden_metrics')
    # ### end Alembic commands ###
