"""add_new_metrics

Revision ID: bf55d8fb5993
Revises: a8012d142ecf
Create Date: 2025-05-17 12:44:50.428460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'bf55d8fb5993'
down_revision: Union[str, None] = 'a8012d142ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            DELETE FROM metrics WHERE name = 'DAU';
            """
        )
    )
    conn.execute(
        sa.text(
            """
            DELETE FROM hidden_metrics WHERE metric_name = 'DAU';
            """
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='metrictype',
        new_values=['TICKETS_SOLD', 'TOTAL_SOLD_TICKETS', 'TOTAL_PRIZE_FUNDS', 'ARPU', 'ARPPU', 'LTV', 'GGR', 'FTD', 'CPA', 'ACTIVE_USERS', 'AVG_SESSION_TIME', 'ALL_GAMES'],
        affected_columns=[TableReference(table_schema='public', table_name='hidden_metrics', column_name='metric_name'), TableReference(table_schema='public', table_name='metrics', column_name='name')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='metrictype',
        new_values=['TOTAL_SOLD_TICKETS', 'ARPU', 'ARPPU', 'LTV', 'GGR', 'FTD', 'CPA', 'DAU', 'AVG_SESSION_TIME'],
        affected_columns=[TableReference(table_schema='public', table_name='hidden_metrics', column_name='metric_name'), TableReference(table_schema='public', table_name='metrics', column_name='name')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
