"""action

Revision ID: 0e1cdd40eade
Revises: 3ee03399a6c5
Create Date: 2025-05-08 10:59:05.876130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e1cdd40eade'
down_revision: Union[str, None] = '3ee03399a6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('TOTAL_SOLD_TICKETS', 'ARPU', 'ARPPU', 'LTV', 'GGR', 'FTD', 'CPA', 'DAU', 'AVG_SESSION_TIME', name='metrictype').create(op.get_bind())
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('name', postgresql.ENUM('TOTAL_SOLD_TICKETS', 'ARPU', 'ARPPU', 'LTV', 'GGR', 'FTD', 'CPA', 'DAU', 'AVG_SESSION_TIME', name='metrictype', create_type=False), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_currency_id'), 'metrics', ['currency_id'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_name'), 'metrics', ['name'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['LOGIN', 'LOGOUT', 'REGISTER', 'DEPOSIT', 'WITHDRAW', 'TRANSACTION', 'UPDATE', 'OTHER', 'ADMIN_LOGIN', 'ADMIN_LOGOUT', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_DELETE'],
        affected_columns=[TableReference(table_schema='public', table_name='user_action_logs', column_name='action')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['LOGIN', 'LOGOUT', 'REGISTER', 'DEPOSIT', 'WITHDRAW', 'TRANSACTION', 'UPDATE', 'ADMIN_LOGIN', 'ADMIN_LOGOUT', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_DELETE'],
        affected_columns=[TableReference(table_schema='public', table_name='user_action_logs', column_name='action')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_metrics_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_currency_id'), table_name='metrics')
    op.drop_table('metrics')
    sa.Enum('TOTAL_SOLD_TICKETS', 'ARPU', 'ARPPU', 'LTV', 'GGR', 'FTD', 'CPA', 'DAU', 'AVG_SESSION_TIME', name='metrictype').drop(op.get_bind())
    # ### end Alembic commands ###
