"""changesv12

Revision ID: 077880b519ea
Revises: 8a588b07669e
Create Date: 2025-03-31 06:45:01.909305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077880b519ea'
down_revision: Union[str, None] = '8a588b07669e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('number', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'tickets', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_column('tickets', 'number')
    # ### end Alembic commands ###
