"""pcs at BalanceChangeHistory

Revision ID: b49866b9d850
Revises: ce84c39b073d
Create Date: 2025-05-22 19:10:52.801036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models


# revision identifiers, used by Alembic.
revision: str = 'b49866b9d850'
down_revision: Union[str, None] = 'ce84c39b073d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_change_history', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_change_history', 'count')
    # ### end Alembic commands ###
