"""user_type

Revision ID: 534021b6dc7e
Revises: 6ebcd78d7750
Create Date: 2025-06-03 07:21:34.960909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '534021b6dc7e'
down_revision: Union[str, None] = '6ebcd78d7750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', postgresql.ENUM('VIP', 'PREMIUM', 'BASIC', name='usertype', create_type=False), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE users
        SET type = 'BASIC'
        WHERE type IS NULL
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    # ### end Alembic commands ###
