"""limit

Revision ID: 88868db49cec
Revises: b49866b9d850
Create Date: 2025-05-23 18:32:30.166261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88868db49cec'
down_revision: Union[str, None] = 'b49866b9d850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CRITICAL', 'NORMAL', 'ESCALATE', 'SOFT', name='risklevel').create(op.get_bind())
    sa.Enum('ACTIVE', 'INACTIVE', name='limitstatus').create(op.get_bind())
    sa.Enum('VIP', 'PREMIUM', 'BASIC', name='usertype').create(op.get_bind())
    sa.Enum('ALWAYS', 'SECOND', 'MINUTE', 'HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='period').create(op.get_bind())
    sa.Enum('ALL', 'WITHDRAWAL', 'PURCHASE', name='operationtype').create(op.get_bind())
    sa.Enum('SUM', 'NUMBER', name='limittype').create(op.get_bind())
    op.create_table('limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('SUM', 'NUMBER', name='limittype', create_type=False), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', postgresql.ENUM('ALL', 'WITHDRAWAL', 'PURCHASE', name='operationtype', create_type=False), nullable=False),
    sa.Column('period', postgresql.ENUM('ALWAYS', 'SECOND', 'MINUTE', 'HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='period', create_type=False), nullable=False),
    sa.Column('user_type', postgresql.ENUM('VIP', 'PREMIUM', 'BASIC', name='usertype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='limitstatus', create_type=False), nullable=False),
    sa.Column('risk', postgresql.ENUM('CRITICAL', 'NORMAL', 'ESCALATE', 'SOFT', name='risklevel', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['last_edited'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limits_id'), 'limits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_limits_id'), table_name='limits')
    op.drop_table('limits')
    sa.Enum('SUM', 'NUMBER', name='limittype').drop(op.get_bind())
    sa.Enum('ALL', 'WITHDRAWAL', 'PURCHASE', name='operationtype').drop(op.get_bind())
    sa.Enum('ALWAYS', 'SECOND', 'MINUTE', 'HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='period').drop(op.get_bind())
    sa.Enum('VIP', 'PREMIUM', 'BASIC', name='usertype').drop(op.get_bind())
    sa.Enum('ACTIVE', 'INACTIVE', name='limitstatus').drop(op.get_bind())
    sa.Enum('CRITICAL', 'NORMAL', 'ESCALATE', 'SOFT', name='risklevel').drop(op.get_bind())
    # ### end Alembic commands ###
