"""empty message

Revision ID: dd7555859013
Revises: 534021b6dc7e
Create Date: 2025-06-05 18:17:57.662852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7555859013'
down_revision: Union[str, None] = '534021b6dc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('kyc', sa.Boolean(), nullable=True))
    op.drop_column('limits', 'user_type')
    op.drop_column('users', 'type')
    sa.Enum('VIP', 'PREMIUM', 'BASIC', name='usertype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('VIP', 'PREMIUM', 'BASIC', name='usertype').create(op.get_bind())
    op.add_column('users', sa.Column('type', postgresql.ENUM('VIP', 'PREMIUM', 'BASIC', name='usertype', create_type=False), autoincrement=False, nullable=True))
    op.add_column('limits', sa.Column('user_type', postgresql.ENUM('VIP', 'PREMIUM', 'BASIC', name='usertype', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('limits', 'kyc')
    # ### end Alembic commands ###
