"""rm unused fields

Revision ID: e89df6fe15f3
Revises: 70804071dfc8
Create Date: 2025-05-22 09:38:24.777283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e89df6fe15f3'
down_revision: Union[str, None] = '70804071dfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_change_history', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('balance_change_history', sa.Column('game_type', postgresql.ENUM('JACKPOT', 'INSTABINGO', 'GAME', name='gametype', create_type=False), nullable=True))
    op.add_column('users', sa.Column('_avatar_v1', src.models.custom_types.FileType(), nullable=True))
    op.drop_column('users', 'avatar_v1')
    op.drop_column('users', 'document')
    op.drop_column('users', 'avatar')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gametype',
        new_values=['JACKPOT', 'INSTABINGO', 'GAME'],
        affected_columns=[TableReference(table_schema='public', table_name='balance_change_history', column_name='game_type'), TableReference(table_schema='public', table_name='games', column_name='game_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gametype',
        new_values=['GLOBAL', 'LOCAL'],
        affected_columns=[TableReference(table_schema='public', table_name='balance_change_history', column_name='game_type'), TableReference(table_schema='public', table_name='games', column_name='game_type')],
        enum_values_to_rename=[],
    )
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('document', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_v1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', '_avatar_v1')
    op.drop_column('balance_change_history', 'game_type')
    op.drop_column('balance_change_history', 'game_id')
    # ### end Alembic commands ###
