"""block

Revision ID: 6ebcd78d7750
Revises: e08a3a9463e5
Create Date: 2025-05-28 16:55:16.683115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6ebcd78d7750'
down_revision: Union[str, None] = 'e08a3a9463e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['PENDING', 'SUCCESS', 'BLOCKED', 'CANCELED', 'INSUFFICIENT_FUNDS', 'WEB3_ERROR'],
        affected_columns=[TableReference(table_schema='public', table_name='balance_change_history', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['PENDING', 'SUCCESS', 'CANCELED', 'INSUFFICIENT_FUNDS', 'WEB3_ERROR'],
        affected_columns=[TableReference(table_schema='public', table_name='balance_change_history', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
