"""rm unused field

Revision ID: ce84c39b073d
Revises: 70804071dfc8
Create Date: 2025-05-22 10:44:07.086703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce84c39b073d'
down_revision: Union[str, None] = '70804071dfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('JACKPOT', 'INSTABINGO', 'GAME', name='gameinstancetype').create(op.get_bind())
    op.add_column('balance_change_history', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('balance_change_history', sa.Column('game_type', postgresql.ENUM('JACKPOT', 'INSTABINGO', 'GAME', name='gameinstancetype', create_type=False), nullable=True))
    op.add_column('users', sa.Column('_avatar_v1', src.models.custom_types.FileType(), nullable=True))
    op.drop_column('users', 'avatar_v1')
    op.drop_column('users', 'document')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('document', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_v1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', '_avatar_v1')
    op.drop_column('balance_change_history', 'game_type')
    op.drop_column('balance_change_history', 'game_id')
    sa.Enum('JACKPOT', 'INSTABINGO', 'GAME', name='gameinstancetype').drop(op.get_bind())
    # ### end Alembic commands ###
