"""OperationType field DEPOSIT

Revision ID: 568a33f0b624
Revises: b603facfe42d
Create Date: 2025-06-19 08:35:30.374494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '568a33f0b624'
down_revision: Union[str, None] = 'b603facfe42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='operationtype',
        new_values=['ALL', 'WITHDRAWAL', 'PURCHASE', 'DEPOSIT'],
        affected_columns=[TableReference(table_schema='public', table_name='limits', column_name='operation_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='operationtype',
        new_values=['ALL', 'WITHDRAWAL', 'PURCHASE'],
        affected_columns=[TableReference(table_schema='public', table_name='limits', column_name='operation_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
