"""empty message

Revision ID: b603facfe42d
Revises: dd7555859013
Create Date: 2025-06-08 09:57:18.631272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b603facfe42d'
down_revision: Union[str, None] = 'dd7555859013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'price')
    # ### end Alembic commands ###
