"""is_deleted

Revision ID: e08a3a9463e5
Revises: 88868db49cec
Create Date: 2025-05-26 18:50:31.079503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models


# revision identifiers, used by Alembic.
revision: str = 'e08a3a9463e5'
down_revision: Union[str, None] = '88868db49cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('limits', 'is_deleted')
    # ### end Alembic commands ###
