"""RM STATUS FIELD(LIMIT)

Revision ID: 070a6a73c6f0
Revises: 568a33f0b624
Create Date: 2025-06-20 07:36:50.491878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '070a6a73c6f0'
down_revision: Union[str, None] = '568a33f0b624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('limits', 'status')
    sa.Enum('ACTIVE', 'INACTIVE', name='limitstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', name='limitstatus').create(op.get_bind())
    op.add_column('limits', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='limitstatus', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
