"""changesv12

Revision ID: 23d00ee3ccf8
Revises: 4ca4919e8c4c
Create Date: 2025-03-06 09:32:22.271565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d00ee3ccf8'
down_revision: Union[str, None] = '4ca4919e8c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jackpots', sa.Column('amount', sa.DECIMAL(precision=9, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jackpots', 'amount')
    # ### end Alembic commands ###
