"""changesv7

Revision ID: 399c66f86cf8
Revises: b39860661072
Create Date: 2025-03-19 17:51:34.513188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399c66f86cf8'
down_revision: Union[str, None] = 'b39860661072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jackpots', sa.Column('numbers', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('jackpots', sa.Column('fund_start', sa.DateTime(), nullable=True))
    op.add_column('jackpots', sa.Column('fund_end', sa.DateTime(), nullable=True))
    op.add_column('jackpots', sa.Column('event_start', sa.DateTime(), nullable=True))
    op.add_column('jackpots', sa.Column('event_end', sa.DateTime(), nullable=True))
    op.drop_column('jackpots', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jackpots', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('jackpots', 'event_end')
    op.drop_column('jackpots', 'event_start')
    op.drop_column('jackpots', 'fund_end')
    op.drop_column('jackpots', 'fund_start')
    op.drop_column('jackpots', 'numbers')
    # ### end Alembic commands ###
