"""changesv13

Revision ID: 6502d121c208
Revises: 3590b16f3570
Create Date: 2025-03-14 14:19:38.331450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6502d121c208'
down_revision: Union[str, None] = '3590b16f3570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instabingos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('prize', sa.DECIMAL(precision=9, scale=2), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    op.create_index(op.f('ix_instabingos_id'), 'instabingos', ['id'], unique=False)
    op.drop_index('ix_game_instances_id', table_name='game_instances')
    op.drop_table('game_instances')
    op.drop_index('ix_jackpot_instances_id', table_name='jackpot_instances')
    op.drop_table('jackpot_instances')
    sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='jackpotstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='jackpotstatus').create(op.get_bind())
    op.create_table('jackpot_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jackpot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='jackpotstatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('scheduled_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['jackpot_id'], ['jackpots.id'], name='jackpot_instances_jackpot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jackpot_instances_pkey')
    )
    op.create_index('ix_jackpot_instances_id', 'jackpot_instances', ['id'], unique=False)
    op.create_table('game_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'DELETED', name='gamestatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('scheduled_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_instances_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_instances_pkey')
    )
    op.create_index('ix_game_instances_id', 'game_instances', ['id'], unique=False)
    op.drop_index(op.f('ix_instabingos_id'), table_name='instabingos')
    op.drop_table('instabingos')
    # ### end Alembic commands ###
