"""changesv9

Revision ID: 849e27acbc35
Revises: 1dfe0cc6f5ca
Create Date: 2025-03-24 14:04:19.822789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '849e27acbc35'
down_revision: Union[str, None] = '1dfe0cc6f5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gamestatus',
        new_values=['NEW', 'PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'DELETED'],
        affected_columns=[TableReference(table_schema='public', table_name='games', column_name='status'), TableReference(table_schema='public', table_name='jackpots', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='gamestatus',
        new_values=['PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'DELETED'],
        affected_columns=[TableReference(table_schema='public', table_name='games', column_name='status'), TableReference(table_schema='public', table_name='jackpots', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
