"""changesv5

Revision ID: c613eb79c358
Revises: 66c783a816b9
Create Date: 2025-02-15 18:44:09.100394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c613eb79c358'
down_revision: Union[str, None] = '66c783a816b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('rpc_url', sa.String(length=255), nullable=False),
    sa.Column('explorer_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_networks_id'), 'networks', ['id'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('private_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('private_key')
    )
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    op.add_column('balance', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.alter_column('balance', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.create_foreign_key(None, 'balance', 'currencies', ['currency_id'], ['id'], ondelete='CASCADE')
    op.add_column('balance_change_history', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('balance_change_history', sa.Column('proof', sa.String(length=256), nullable=True))
    op.alter_column('balance_change_history', 'change_amount',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=20, scale=8),
               nullable=True)
    op.alter_column('balance_change_history', 'new_balance',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=20, scale=8),
               nullable=True)
    op.create_foreign_key(None, 'balance_change_history', 'currencies', ['currency_id'], ['id'], ondelete='CASCADE')
    op.add_column('currencies', sa.Column('network_id', sa.Integer(), nullable=True))
    op.add_column('currencies', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('currencies', sa.Column('decimals', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'currencies', 'networks', ['network_id'], ['id'])
    op.add_column('games', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'currencies', ['currency_id'], ['id'])
    op.alter_column('jackpots', '_type',
               existing_type=postgresql.ENUM('GLOBAL', 'LOCAL', name='jackpottype'),
               nullable=True)
    op.add_column('tickets', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'currencies', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'currency_id')
    op.alter_column('jackpots', '_type',
               existing_type=postgresql.ENUM('GLOBAL', 'LOCAL', name='jackpottype'),
               nullable=False)
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'currency_id')
    op.drop_constraint(None, 'currencies', type_='foreignkey')
    op.drop_column('currencies', 'decimals')
    op.drop_column('currencies', 'address')
    op.drop_column('currencies', 'network_id')
    op.drop_constraint(None, 'balance_change_history', type_='foreignkey')
    op.alter_column('balance_change_history', 'new_balance',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('balance_change_history', 'change_amount',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('balance_change_history', 'proof')
    op.drop_column('balance_change_history', 'currency_id')
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.alter_column('balance', 'balance',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('balance', 'currency_id')
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index(op.f('ix_networks_id'), table_name='networks')
    op.drop_table('networks')
    # ### end Alembic commands ###
