"""avatars

Revision ID: d20a701c35ee
Revises: 92a03ff9ff84
Create Date: 2025-04-16 09:40:50.140530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd20a701c35ee'
down_revision: Union[str, None] = '92a03ff9ff84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_v1', src.models.custom_types.FileType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_v1')
    # ### end Alembic commands ###
