"""changesv4

Revision ID: f8af0e065fab
Revises: 0c66f6ab8c43
Create Date: 2025-03-17 20:52:41.769673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8af0e065fab'
down_revision: Union[str, None] = '0c66f6ab8c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instabingos', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('instabingos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('instabingos_country_key', 'instabingos', type_='unique')
    op.add_column('numbers', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.drop_constraint('numbers_instabingo_id_fkey', 'numbers', type_='foreignkey')
    op.create_foreign_key(None, 'numbers', 'tickets', ['ticket_id'], ['id'])
    op.drop_column('numbers', 'instabingo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('numbers', sa.Column('instabingo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'numbers', type_='foreignkey')
    op.create_foreign_key('numbers_instabingo_id_fkey', 'numbers', 'instabingos', ['instabingo_id'], ['id'])
    op.drop_column('numbers', 'ticket_id')
    op.create_unique_constraint('instabingos_country_key', 'instabingos', ['country'])
    op.drop_column('instabingos', 'created_at')
    op.drop_column('instabingos', 'deleted')
    # ### end Alembic commands ###
